import "./styles.js";

let docs = [
  { id: "d1", name: "2024 수도권 DRT 도입 검토 보고서.pdf", type: "PDF", date: "2024. 11. 08", pages: 84, size: "12.4 MB", status: "완료", source: "사용 가능", topic: "수요응답형 교통 도입 검토", summary: "수도권 교통취약지역을 중심으로 DRT 도입 조건과 운영 대안을 검토한 보고서입니다.", units: [
    { range: "p. 12–14", match: "p. 13", score: 96, title: "교통취약지역 선정을 위한 기준", text: "교통취약지역은 대중교통 접근성, 고령인구 비율, 정류장 반경 내 인구밀도와 기존 노선의 운행 간격을 종합하여 선정한다.", tags: ["교통취약지역", "선정 기준", "DRT"] },
    { range: "p. 35–37", match: "p. 36", score: 89, title: "DRT 도입 시나리오", text: "고정노선의 수요가 낮은 지역은 시간대별 예약 기반 수요응답형 운송을 우선 검토할 수 있다.", tags: ["DRT", "수요응답형", "운영"] }
  ] },
  { id: "d2", name: "대중교통 이용행태 변화 분석_최종.pptx", type: "PPTX", date: "2025. 03. 17", pages: 42, size: "8.7 MB", status: "부분 완료", source: "사용 가능", topic: "버스 이용객 감소 원인 분석", summary: "코로나 이후 통행 패턴과 버스 이용객 감소 요인을 분석한 발표자료입니다.", units: [
    { range: "슬라이드 18", match: "슬라이드 18", score: 91, title: "버스 이용객 감소 요인", text: "재택근무 확산, 승용차 전환, 배차간격 증가가 평일 버스 이용객 감소의 주요 요인으로 확인되었다.", tags: ["버스", "이용객 감소", "통행 패턴"], visual: true },
    { range: "슬라이드 24–25", match: "슬라이드 24", score: 78, title: "권역별 수요 변화", text: "외곽 권역의 감소 폭이 중심 권역보다 크게 나타났으며, 환승 불편이 주요 설명변수로 나타났다.", tags: ["수요", "환승", "권역"] }
  ] },
  { id: "d3", name: "2023 생활SOC 접근성 개선 연구.docx", type: "DOCX", date: "2023. 08. 29", pages: 126, size: "4.1 MB", status: "완료", source: "원본 누락", topic: "생활권 접근성 지표 연구", summary: "생활SOC와 대중교통 접근성의 관계를 평가하는 지표와 적용 사례를 정리했습니다.", units: [
    { range: "p. 48–50", match: "p. 49", score: 72, title: "접근성 평가 지표", text: "접근성은 이동시간, 서비스 빈도, 보행 연결성과 취약계층의 이동 제약을 함께 고려해 평가한다.", tags: ["접근성", "취약계층", "평가"] }
  ] }
];

let state = { page: "search", query: "", apiResults: [], shownResults: 5, jobs: [], maintenance: false, toast: "" };

const icons = { search:"⌕", add:"＋", docs:"▤", settings:"⚙", spark:"✦", arrow:"→", close:"×", pause:"Ⅱ", play:"▶", more:"⋯", file:"▧", check:"✓", alert:"!" };
const escape = (s) => String(s).replace(/[&<>"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const formatResults = () => {
  if (state.apiResults.length) return state.apiResults.map((result) => ({ doc: { id: result.documentId, name: result.fileName, type: result.format }, unit: { range: `${result.locationPrefix || 'p.'} ${result.sourceRange}`, match: `${result.locationPrefix || 'p.'} ${result.matchedPage}`, score: result.score, title: result.evidenceType === "visual" ? "시각 근거 OCR" : result.evidenceType === "table" ? "표 셀 근거" : "원문 근거", text: result.text, visual: result.evidenceType === "visual" && result.visualAssetName ? `/api/documents/${result.documentId}/visual/${encodeURIComponent(result.visualAssetName)}` : null, tags: [result.evidenceType === "text" ? "Text Evidence" : result.evidenceType === "table" ? "Table Evidence" : "Visual Evidence", result.evidenceOrigin === "native" ? "원문 추출" : result.evidenceOrigin === "ocr" ? "OCR 추출" : "원문 + OCR", result.lowRelevance ? "낮은 연관성" : "매칭됨"] } }));
  return [];
};
function nav(){ return `<aside class="sidebar"><a class="brand" data-nav="search"><span class="brand-mark">w</span><span>Weki</span></a><div class="kb-chip"><span class="pulse"></span><span>MY KNOWLEDGE BASE</span><b>${docs.length} docs</b></div><nav>${[["search","검색",icons.search],["add","문서 등록",icons.add],["documents","문서 관리",icons.docs],["settings","설정 · 운영",icons.settings]].map(([key,label,icon])=>`<button class="nav-item ${state.page===key?"active":""}" data-nav="${key}"><i>${icon}</i>${label}</button>`).join("")}</nav><div class="sidebar-bottom"><div class="storage"><span>저장소 사용량</span><strong>25.2 <small>GB</small></strong><div><b style="width:28%"></b></div><em>90 GB 사용 가능</em></div><button class="help">?&nbsp; Weki 사용 가이드</button></div></aside>` }
function topbar(eyebrow,title,subtitle,action=""){return `<header class="topbar"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${subtitle?`<p class="subtitle">${subtitle}</p>`:""}</div>${action}</header>`}
function searchPage(){ const results=formatResults(); return `<main>${topbar("EVIDENCE SEARCH","무엇을 찾고 있나요?","등록한 문서에서 실제 근거와 위치를 찾아드려요.")}<section class="search-hero"><div class="querybox"><span>${icons.spark}</span><input id="query" value="${escape(state.query)}" placeholder="예: DRT 도입을 검토한 자료 찾아줘"/><button id="run-search" aria-label="검색">${icons.arrow}</button></div><div class="suggestions"><span>이렇게 물어보세요</span><button data-query="교통취약지역 선정 기준이 들어간 보고서">교통취약지역 선정 기준</button><button data-query="버스 이용객 감소 원인을 분석한 자료">버스 이용객 감소 원인</button></div></section>${!docs.length?'<div class="empty-state"><div>▧</div><h2>아직 등록된 문서가 없습니다</h2><p>문서를 등록하면 자연어로 필요한 실제 근거를 검색할 수 있습니다.</p><button class="primary" data-nav="add">문서 등록 시작</button></div>':`<section class="result-head"><div><p class="eyebrow">SEARCH RESULTS</p><h2><b>${results.length}</b>개의 근거를 찾았어요</h2></div><div class="search-status"><span class="good-dot"></span> Local FTS 정상</div></section><div class="lowrel"><span>i</span><div><b>모든 결과를 보여드려요</b><p>연관성이 낮은 결과도 실제 근거와 위치를 함께 표시합니다.</p></div></div><div class="results">${results.map((r,i)=>resultCard(r,i)).join("")}</div>`}</main>` }
function resultCard({doc,unit}, i){ return `<article class="result-card"><div class="rank">0${i+1}</div><div class="result-main"><div class="doc-line"><span class="filetype ${doc.type.toLowerCase()}">${doc.type}</span><span>${doc.name}</span><button class="dot-btn">${icons.more}</button></div><h3>${unit.title}</h3><p class="evidence-text">${unit.text}</p><div class="tags">${unit.tags.map(t=>`<span>${t}</span>`).join("")}</div>${unit.visual?`<div class="visual-preview"><img src="${unit.visual}" alt="슬라이드 시각 근거"/><small>원본 슬라이드 시각 근거</small></div>`:""}<footer><div class="location"><span>근거 위치</span><b>${unit.match}</b><i></i><span>관련 범위 ${unit.range}</span></div><div class="score" title="검색 알고리즘이 여러 요소를 종합해 산정한 상대적 지표이며, 일치율이나 정확도를 의미하지 않습니다."><span>검색 연관성 지표</span><b>${unit.score}</b><div><i style="width:${unit.score}%"></i></div></div></footer><div class="card-actions"><a class="open-source" href="/api/documents/${doc.id}/original">원본 열기 ${icons.arrow}</a><button class="feedback" data-feedback="${doc.id}" data-helpful="true">관련 있음 ${icons.check}</button><button class="feedback" data-feedback="${doc.id}" data-helpful="false">관련 없음</button></div></div></article>`}
function addPage(){ const running=state.jobs.find(j=>j.status==='processing');return `<main>${topbar("INGESTION","문서 등록", "파일을 내부 저장소에 보관하고, 페이지별 실제 텍스트를 로컬 색인에 추가합니다.")}<div class="split"><section class="upload-panel"><p class="eyebrow">NEW PROCESSING JOB</p><h2>무엇을 등록할까요?</h2><input id="file-input" type="file" multiple accept=".pdf,.pptx,.docx,.hwpx,.hwp" hidden /><div class="dropzone"><div class="drop-icon">${icons.add}</div><h3>지원 문서를 선택하세요</h3><p>PDF, PPTX, HWP, HWPX, DOCX · 최대 200 MB/파일</p><div><button class="secondary" id="choose-files">파일 선택</button></div></div><label class="field-label">처리 모드</label><div class="modes"><label class="mode selected"><input type="radio" checked value="lightweight" name="mode"/><span><b>경량 처리만</b><small>로컬 Parsing 및 페이지별 텍스트 색인</small></span><em>기본</em></label><label class="mode"><input type="radio" value="local-ai" name="mode"/><span><b>Local AI 허용</b><small>현재는 로컬 경량 추출로 처리</small></span></label><label class="mode external"><input type="radio" value="external-ai" name="mode"/><span><b>External AI 허용</b><small>이 MVP는 외부로 문서를 전송하지 않음</small></span></label></div><button class="primary wide" id="create-job">선택 파일 등록 ${icons.arrow}</button></section><section class="queue-panel"><div class="section-title"><div><p class="eyebrow">PROCESSING QUEUE</p><h2>처리 현황 <b>${state.jobs.length}</b></h2></div><span class="queue-state">${running?"1개 실행 중":"대기 없음"}</span></div>${state.jobs.map(job=>jobCard(job)).join("")}<div class="queue-note"><span>i</span><p>추출에 성공한 페이지는 Text Evidence와 정확한 페이지 번호를 보존해 검색합니다.</p></div></section></div></main>`}
function jobCard(j){ const status={processing:"처리 중",queued:"대기",paused:"일시중지",completed:"완료",skipped:"건너뜀",failed:"실패"}[j.status] || j.status; return `<article class="job ${j.status}"><div class="job-top"><span class="job-state">${j.status==='processing'?'<i class="spinner"></i>':j.status==='completed'?'✓':j.status==='failed'?'!':j.status==='queued'?'02':'Ⅱ'} ${status}</span><button class="dot-btn">${icons.more}</button></div><h3>${j.name}</h3><p>${j.kind || 'registration'} · ${j.mode || 'lightweight'}</p><div class="job-progress"><div><b>${j.detail}</b><span>${j.progress ?? 0}%</span></div><i><em style="width:${j.progress ?? 0}%"></em></i></div>${['completed','skipped','failed'].includes(j.status)?'':`<div class="job-actions">${j.status==='processing'?`<button data-job="pause" data-id="${j.id}">${icons.pause} 일시중지</button><button data-job="cancel" data-id="${j.id}">${icons.close} 취소</button>`:j.status==='queued'?`<button data-job="start" data-id="${j.id}">${icons.play} 지금 시작</button><button data-job="cancel" data-id="${j.id}">${icons.close} 대기 제거</button>`:`<button data-job="start" data-id="${j.id}">${icons.play} 재개</button><button data-job="cancel" data-id="${j.id}">${icons.close} 취소</button>`}</div>`}</article>`}
function documentsPage(){return `<main>${topbar("LIBRARY","문서 관리", `${docs.length}개 문서 · 로컬 저장소`, '<button class="primary" data-nav="add">${icons.add} 문서 등록</button>')}<div class="toolbar"><div class="mini-search">⌕ <input placeholder="문서 이름 검색"/></div><button>상태: 전체⌄</button><span></span><button>정렬: 최근 등록순⌄</button></div>${docs.length?`<section class="doc-table"><div class="table-head"><span>문서</span><span>상태</span><span>원본</span><span>등록일</span><span></span></div>${docs.map(d=>`<article class="doc-row"><div class="doc-name"><span class="filetype ${d.type.toLowerCase()}">${d.type}</span><div><b>${d.name}</b><small>${d.pages} 페이지 · ${(Number(d.size)/1024/1024).toFixed(1)} MB · OCR: ${d.ocrStatus === 'success' ? '완료' : d.ocrStatus === 'unavailable' ? '엔진 미설치' : '대기'}</small></div></div><span class="status ${d.processingStatus === 'partial' ? 'partial' : 'complete'}">${d.processingStatus === 'partial' ? '!' : '✓'} ${d.processingStatus === 'partial' ? '부분 완료' : '완료'}</span><span class="source ${d.source==='사용 가능'?'available':'missing'}">${d.source==='사용 가능'?'●':'○'} ${d.source}</span><span>${d.date}</span><div class="row-actions"><button data-reprocess="${d.id}">재처리</button><button data-delete="${d.id}" class="delete">삭제</button></div></article>`).join("")}</section>`:'<div class="empty-state"><div>▧</div><h2>등록된 문서가 없습니다</h2><p>문서를 등록하면 로컬 검색 인덱스를 생성합니다.</p></div>'}<div class="details-card"><div><p class="eyebrow">STORAGE & INTEGRITY</p><h3>검색 데이터 상태</h3><p>원문 기반 Text Evidence와 페이지 Provenance를 로컬 저장소에 보존합니다. OCR 미설치 상태도 숨기지 않습니다.</p></div><button class="secondary" data-toast="저장소 상태를 확인했습니다">상세 확인</button></div></main>`}
function settingsPage(){const lock=state.jobs.some(job=>['queued','processing','paused'].includes(job.status));return `<main>${topbar("SETTINGS & OPERATIONS","설정 · 운영", "저장소, AI 처리, 백업과 보안을 관리합니다.")}<div class="settings-grid"><section class="settings-card span2"><p class="eyebrow">LOCAL STORAGE</p><h2>내부 저장소</h2><div class="path"><span>▰</span><code>프로젝트 내부 .weki-data</code></div><p class="muted">등록된 원본과 검색 데이터는 이 로컬 저장소에서 관리됩니다.</p></section><section class="settings-card"><p class="eyebrow">AI DEFAULT</p><h2>기본 처리 모드</h2><div class="select-row"><b>경량 처리만</b><span>⌄</span></div><p class="muted">AI 없이도 핵심 검색 기능이 동작합니다.</p></section><section class="settings-card"><p class="eyebrow">RETRIEVAL</p><h2>검색 엔진 상태</h2><div class="engine"><span class="good-dot"></span><b>로컬 Vector Search</b><em>정상</em></div><div class="engine"><span class="good-dot"></span><b>로컬 FTS</b><em>정상</em></div></section><section class="settings-card span2"><p class="eyebrow">MAINTENANCE</p><h2>암호화 백업 및 복원</h2><p class="muted">Queue가 비어 있을 때만 시작할 수 있습니다. API Key는 백업에 포함되지 않습니다. 복원은 현재 데이터를 선택한 백업으로 전체 교체합니다.</p><input id="backup-passphrase" class="backup-input" type="password" minlength="8" placeholder="백업 또는 복원 암호 (8자 이상)" autocomplete="new-password"/><input id="restore-file" type="file" accept=".weki,application/json" hidden/><div class="maintenance-actions"><button class="secondary ${lock?'disabled':''}" data-backup="search">검색 시스템 백업</button><button class="secondary ${lock?'disabled':''}" data-backup="full">전체 백업</button><button class="secondary ${lock?'disabled':''}" id="choose-restore">백업 파일 복원</button></div><small class="muted">검색 시스템 백업을 복원하면 원본 파일은 ‘누락’ 상태가 되며, 동일 Hash 파일을 다시 등록해 재연결할 수 있습니다.</small>${lock?'<div class="blocked">! 현재 처리 Queue가 비어 있지 않아 Maintenance 작업을 시작할 수 없습니다.</div>':''}</section><section class="settings-card"><p class="eyebrow">SYNONYMS</p><h2>동의어 · 약어</h2><input id="synonym-term" class="backup-input" placeholder="기준어 (예: 결제)"/><input id="synonym-aliases" class="backup-input" placeholder="동의어를 쉼표로 구분 (예: payment, pay)"/><button class="secondary" id="save-synonym">검색 확장어 저장</button><div id="synonym-list" class="muted">불러오는 중…</div></section><section class="settings-card"><p class="eyebrow">AUDIT</p><h2>최근 작업 기록</h2><div id="audit-list" class="muted">불러오는 중…</div></section><section class="settings-card danger"><p class="eyebrow">DATA</p><h2>전체 문서 데이터 삭제</h2><p class="muted">문서, 검색 데이터, 내부 원본을 영구 제거합니다. 확인 문구를 입력하세요.</p><input id="delete-confirmation" class="backup-input" placeholder="DELETE ALL DOCUMENTS"/><button class="danger-btn ${lock?'disabled':''}" id="delete-all-data">전체 데이터 영구 삭제</button></section></div></main>`}
function render(){const views={search:searchPage,add:addPage,documents:documentsPage,settings:settingsPage};document.querySelector('#app').innerHTML=`<div class="app-shell">${nav()}${views[state.page]()}${state.toast?`<div class="toast">${state.toast}<button data-close-toast>×</button></div>`:""}</div>`; bind(); wireJobControls(); wireFeedbackControls(); if(state.page==="settings") wireOperations();}
function wireJobControls(){document.querySelectorAll('[data-job]').forEach(button=>button.onclick=async()=>{const action=button.dataset.job;const response=await fetch(`/api/jobs/${button.dataset.id}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const data=await response.json();await refreshDocuments();state.toast=response.ok?data.job.detail:data.error;render();});}
function wireFeedbackControls(){document.querySelectorAll('[data-feedback]').forEach(button=>button.onclick=async()=>{const helpful=button.dataset.helpful!=="false";const response=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:state.query,documentId:button.dataset.feedback,helpful})});state.toast=response.ok?(helpful?'관련 있음 피드백을 기록했어요':'관련 없음 피드백을 기록했어요'):'피드백 기록에 실패했습니다.';render();});}
async function wireOperations(){
  const synonymList=document.querySelector('#synonym-list'); const auditList=document.querySelector('#audit-list');
  try { const response=await fetch('/api/synonyms'); const data=await response.json(); if(synonymList) synonymList.innerHTML=data.entries.length?data.entries.map(entry=>`<div>${escape(entry.term)} → ${escape(entry.aliases.join(', '))} <button data-remove-synonym="${entry.id}">삭제</button></div>`).join(''):'등록된 검색 확장어가 없습니다.'; document.querySelectorAll('[data-remove-synonym]').forEach(button=>button.onclick=async()=>{await fetch(`/api/synonyms/${button.dataset.removeSynonym}`,{method:'DELETE'});wireOperations();}); } catch { if(synonymList) synonymList.textContent='동의어 목록을 불러오지 못했습니다.'; }
  try { const response=await fetch('/api/audit'); const data=await response.json(); if(auditList) auditList.innerHTML=data.entries.length?data.entries.slice(0,8).map(entry=>`<div>${new Date(entry.createdAt).toLocaleString('ko-KR')} · ${escape(entry.type)} · ${escape(entry.detail)}</div>`).join(''):'기록이 없습니다.'; } catch { if(auditList) auditList.textContent='작업 기록을 불러오지 못했습니다.'; }
  document.querySelector('#save-synonym')?.addEventListener('click',async()=>{const term=document.querySelector('#synonym-term')?.value||'';const aliases=(document.querySelector('#synonym-aliases')?.value||'').split(',').map(item=>item.trim()).filter(Boolean);const response=await fetch('/api/synonyms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({term,aliases})});const data=await response.json();state.toast=response.ok?'검색 확장어를 저장했습니다.':data.error;render();});
  document.querySelector('#choose-restore')?.addEventListener('click',()=>document.querySelector('#restore-file')?.click());
  document.querySelector('#restore-file')?.addEventListener('change',async(event)=>{const file=event.target.files?.[0];const passphrase=document.querySelector('#backup-passphrase')?.value||'';if(!file)return;if(passphrase.length<8){state.toast='복원 암호를 8자 이상 입력해 주세요.';render();return;}if(!confirm('현재 데이터가 선택한 백업 시점의 상태로 덮어써집니다. 복원을 계속할까요?')){event.target.value='';return;}const form=new FormData();form.append('backup',file);form.append('passphrase',passphrase);const response=await fetch('/api/backups/restore',{method:'POST',body:form});const data=await response.json();if(response.ok){await refreshDocuments();state.toast=`${data.documents}개 문서를 ${data.type==='search'?'검색 시스템':'전체'} 백업에서 복원했습니다.`;}else state.toast=data.error||'복원에 실패했습니다.';render();});
  document.querySelector('#delete-all-data')?.addEventListener('click',async()=>{const confirmation=document.querySelector('#delete-confirmation')?.value||'';if(confirmation!=='DELETE ALL DOCUMENTS'){state.toast='확인 문구가 일치하지 않습니다.';render();return;}if(!confirm('문서·검색 데이터·내부 원본이 영구 삭제됩니다. 계속할까요?'))return;if(!confirm('마지막 확인: 이 작업은 되돌릴 수 없습니다.'))return;const response=await fetch('/api/data',{method:'DELETE',headers:{'x-weki-confirmation':confirmation}});if(response.ok){await refreshDocuments();state.toast='전체 문서 데이터가 삭제되었습니다.';}else {const data=await response.json();state.toast=data.error||'삭제에 실패했습니다.';}render();});
}
async function refreshDocuments() {
  const response = await fetch("/api/documents");
  const data = await response.json();
  docs = data.documents.map((doc) => ({
    ...doc,
    type: doc.format,
    status: "완료",
    source: doc.sourceStatus === "available" ? "사용 가능" : "원본 누락",
    date: new Date(doc.registeredAt).toLocaleDateString("ko-KR"),
    topic: "로컬 페이지별 텍스트 색인"
  }));
  const jobsResponse = await fetch("/api/jobs");
  const jobsData = await jobsResponse.json();
  state.jobs = jobsData.jobs.slice(0, 12);
}
async function runSearch() {
  const query = document.querySelector("#query")?.value || state.query;
  state.query = query;
  const previous = state.apiResults;
  if (/^PDF만$/i.test(query.trim()) || /^(PPT|PPTX)만$/i.test(query.trim())) { const format = query.toUpperCase().startsWith("PDF") ? "PDF" : "PPTX"; state.apiResults = previous.filter((result) => result.format === format); state.toast = `현재 검색 세션에서 ${format} 결과만 표시합니다.`; render(); return; }
  const effectiveQuery = /두 ?번째 결과.*(유사|비슷)/.test(query) && previous[1] ? previous[1].text : query;
  const response = await fetch("/api/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query: effectiveQuery }) });
  const data = await response.json();
  state.apiResults = data.results;
  state.toast = data.expansions?.length ? `검색 확장: ${data.expansions.join(", ")}` : effectiveQuery !== query ? "두 번째 결과를 기준으로 유사 근거를 다시 찾았습니다." : "";
  render();
}
async function uploadFiles() {
  const input = document.querySelector("#file-input");
  if (!input.files?.length) { state.toast = "등록할 파일을 먼저 선택해 주세요."; render(); return; }
  const mode = document.querySelector('input[name="mode"]:checked')?.value || "lightweight";
  state.jobs = [...input.files].map((file, index) => ({ id: Date.now() + index, name: file.name, mode, progress: 30, status: "processing", detail: "원본 저장 및 텍스트 추출 중" })); render();
  const form = new FormData(); [...input.files].forEach((file) => form.append("files", file)); form.append("mode", mode);
  try {
    const response = await fetch("/api/documents", { method: "POST", body: form });
    const data = await response.json();
    state.jobs = data.results.map((item, index) => ({ id: Date.now() + index, name: item.name, mode, progress: item.status === "completed" ? 100 : 0, status: item.status === "completed" ? "paused" : "paused", detail: item.status === "completed" ? `${item.pages}개 페이지 색인 완료` : item.error || item.message }));
    await refreshDocuments();
    state.toast = data.results.map((item) => `${item.name}: ${item.status === "queued" ? "대기열 등록" : item.status === "completed" ? "등록 완료" : item.status === "skipped" ? "이미 등록됨" : "실패"}`).join(" · ");
  } catch { state.toast = "문서 등록 중 네트워크 오류가 발생했습니다."; }
  render();
}
function bind(){document.querySelectorAll('[data-nav]').forEach(el=>el.onclick=()=>{state.page=el.dataset.nav;render()});document.querySelectorAll('[data-query]').forEach(el=>el.onclick=async()=>{state.query=el.dataset.query;await runSearch()});const run=document.querySelector('#run-search');if(run)run.onclick=runSearch;const input=document.querySelector('#query');if(input)input.onkeydown=e=>{if(e.key==='Enter')runSearch()};document.querySelectorAll('[data-toast]').forEach(el=>el.onclick=()=>{state.toast=el.dataset.toast;render();setTimeout(()=>{state.toast="";render()},2600)});document.querySelectorAll('[data-close-toast]').forEach(el=>el.onclick=()=>{state.toast="";render()});document.querySelectorAll('[data-feedback]').forEach(el=>el.onclick=async()=>{await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:state.query,documentId:el.dataset.feedback,helpful:true})});state.toast='검색 피드백을 기록했어요';render()});document.querySelectorAll('[data-reprocess]').forEach(el=>el.onclick=async()=>{state.toast='기존 검색 결과를 유지한 채 재처리 중입니다.';render();const response=await fetch(`/api/documents/${el.dataset.reprocess}/reprocess`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'lightweight'})});const data=await response.json();await refreshDocuments();state.toast=response.ok?data.job.detail:data.error;render()});document.querySelectorAll('[data-delete]').forEach(el=>el.onclick=async()=>{if(!confirm('이 문서와 검색 데이터를 삭제할까요?'))return;await fetch(`/api/documents/${el.dataset.delete}`,{method:'DELETE'});await refreshDocuments();state.toast='문서와 검색 데이터가 삭제되었습니다.';render()});document.querySelectorAll('[data-backup]').forEach(el=>el.onclick=async()=>{const passphrase=document.querySelector('#backup-passphrase')?.value||'';if(passphrase.length<8){state.toast='백업 암호를 8자 이상 입력해 주세요.';render();return;}const response=await fetch('/api/backups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:el.dataset.backup,passphrase})});const data=await response.json();state.toast=response.ok?`${data.fileName} 백업을 만들었습니다.`:data.error;render()});document.querySelector('#choose-files')?.addEventListener('click',()=>document.querySelector('#file-input').click());document.querySelector('#create-job')?.addEventListener('click',uploadFiles);document.querySelectorAll('[data-job]').forEach(el=>el.onclick=()=>{const j=state.jobs.find(x=>x.id===Number(el.dataset.id));if(el.dataset.job==='cancel')state.jobs=state.jobs.filter(x=>x!==j);else {state.jobs.forEach(x=>{if(x.status==='processing')x.status='queued'});j.status=el.dataset.job==='pause'?'paused':'processing';} render()});document.querySelectorAll('[data-maint]').forEach(el=>el.onclick=()=>{if(state.jobs.some(job=>['queued','processing','paused'].includes(job.status))){state.toast="Queue가 비어 있어야 이 작업을 시작할 수 있습니다.";render()}else{state.toast=`${el.dataset.maint} 작업을 시작할 수 있습니다.`;render()}})}
refreshDocuments().then(render).catch(() => { state.toast = "로컬 저장소 연결에 실패했습니다."; render(); });
